/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ReturnsNewRouteImport } from './routes/returns.new'
import { Route as SellIndexRouteImport } from './routes/sell.index'
import { Route as SellAddProductRouteImport } from './routes/sell.add-product'
import { Route as SellBulkStockRouteImport } from './routes/sell.bulk-stock'
import { Route as SellBulkUploadRouteImport } from './routes/sell.bulk-upload'
import { Route as SellOnboardingRouteImport } from './routes/sell.onboarding'
import { Route as SellTeamRouteImport } from './routes/sell.team'
import { Route as SellerSlugRouteImport } from './routes/seller.$slug'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api.webhooks.stripe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsNewRoute = ReturnsNewRouteImport.update({
  id: '/returns/new',
  path: '/returns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SellIndexRoute = SellIndexRouteImport.update({
  id: '/sell/',
  path: '/sell/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellAddProductRoute = SellAddProductRouteImport.update({
  id: '/sell/add-product',
  path: '/sell/add-product',
  getParentRoute: () => rootRouteImport,
} as any)
const SellBulkStockRoute = SellBulkStockRouteImport.update({
  id: '/sell/bulk-stock',
  path: '/sell/bulk-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const SellBulkUploadRoute = SellBulkUploadRouteImport.update({
  id: '/sell/bulk-upload',
  path: '/sell/bulk-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SellOnboardingRoute = SellOnboardingRouteImport.update({
  id: '/sell/onboarding',
  path: '/sell/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SellTeamRoute = SellTeamRouteImport.update({
  id: '/sell/team',
  path: '/sell/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerSlugRoute = SellerSlugRouteImport.update({
  id: '/seller/$slug',
  path: '/seller/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/policies': typeof PoliciesRoute
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/api/health': typeof ApiHealthRoute
  '/category/$slug': typeof CategorySlugRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$id': typeof ProductIdRoute
  '/returns/new': typeof ReturnsNewRoute
  '/sell/add-product': typeof SellAddProductRoute
  '/sell/bulk-stock': typeof SellBulkStockRoute
  '/sell/bulk-upload': typeof SellBulkUploadRoute
  '/sell/onboarding': typeof SellOnboardingRoute
  '/sell/team': typeof SellTeamRoute
  '/seller/$slug': typeof SellerSlugRoute
  '/sell/': typeof SellIndexRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/policies': typeof PoliciesRoute
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/api/health': typeof ApiHealthRoute
  '/category/$slug': typeof CategorySlugRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$id': typeof ProductIdRoute
  '/returns/new': typeof ReturnsNewRoute
  '/sell/add-product': typeof SellAddProductRoute
  '/sell/bulk-stock': typeof SellBulkStockRoute
  '/sell/bulk-upload': typeof SellBulkUploadRoute
  '/sell/onboarding': typeof SellOnboardingRoute
  '/sell/team': typeof SellTeamRoute
  '/seller/$slug': typeof SellerSlugRoute
  '/sell': typeof SellIndexRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/policies': typeof PoliciesRoute
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/api/health': typeof ApiHealthRoute
  '/category/$slug': typeof CategorySlugRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$id': typeof ProductIdRoute
  '/returns/new': typeof ReturnsNewRoute
  '/sell/add-product': typeof SellAddProductRoute
  '/sell/bulk-stock': typeof SellBulkStockRoute
  '/sell/bulk-upload': typeof SellBulkUploadRoute
  '/sell/onboarding': typeof SellOnboardingRoute
  '/sell/team': typeof SellTeamRoute
  '/seller/$slug': typeof SellerSlugRoute
  '/sell/': typeof SellIndexRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/policies'
    | '/search'
    | '/signin'
    | '/api/health'
    | '/category/$slug'
    | '/orders/$id'
    | '/product/$id'
    | '/returns/new'
    | '/sell/add-product'
    | '/sell/bulk-stock'
    | '/sell/bulk-upload'
    | '/sell/onboarding'
    | '/sell/team'
    | '/seller/$slug'
    | '/sell/'
    | '/api/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/policies'
    | '/search'
    | '/signin'
    | '/api/health'
    | '/category/$slug'
    | '/orders/$id'
    | '/product/$id'
    | '/returns/new'
    | '/sell/add-product'
    | '/sell/bulk-stock'
    | '/sell/bulk-upload'
    | '/sell/onboarding'
    | '/sell/team'
    | '/seller/$slug'
    | '/sell'
    | '/api/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/policies'
    | '/search'
    | '/signin'
    | '/api/health'
    | '/category/$slug'
    | '/orders/$id'
    | '/product/$id'
    | '/returns/new'
    | '/sell/add-product'
    | '/sell/bulk-stock'
    | '/sell/bulk-upload'
    | '/sell/onboarding'
    | '/sell/team'
    | '/seller/$slug'
    | '/sell/'
    | '/api/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  PoliciesRoute: typeof PoliciesRoute
  SearchRoute: typeof SearchRoute
  SigninRoute: typeof SigninRoute
  ApiHealthRoute: typeof ApiHealthRoute
  CategorySlugRoute: typeof CategorySlugRoute
  OrdersIdRoute: typeof OrdersIdRoute
  ProductIdRoute: typeof ProductIdRoute
  ReturnsNewRoute: typeof ReturnsNewRoute
  SellAddProductRoute: typeof SellAddProductRoute
  SellBulkStockRoute: typeof SellBulkStockRoute
  SellBulkUploadRoute: typeof SellBulkUploadRoute
  SellOnboardingRoute: typeof SellOnboardingRoute
  SellTeamRoute: typeof SellTeamRoute
  SellerSlugRoute: typeof SellerSlugRoute
  SellIndexRoute: typeof SellIndexRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns/new': {
      id: '/returns/new'
      path: '/returns/new'
      fullPath: '/returns/new'
      preLoaderRoute: typeof ReturnsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/': {
      id: '/sell/'
      path: '/sell'
      fullPath: '/sell/'
      preLoaderRoute: typeof SellIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/add-product': {
      id: '/sell/add-product'
      path: '/sell/add-product'
      fullPath: '/sell/add-product'
      preLoaderRoute: typeof SellAddProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/bulk-stock': {
      id: '/sell/bulk-stock'
      path: '/sell/bulk-stock'
      fullPath: '/sell/bulk-stock'
      preLoaderRoute: typeof SellBulkStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/bulk-upload': {
      id: '/sell/bulk-upload'
      path: '/sell/bulk-upload'
      fullPath: '/sell/bulk-upload'
      preLoaderRoute: typeof SellBulkUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/onboarding': {
      id: '/sell/onboarding'
      path: '/sell/onboarding'
      fullPath: '/sell/onboarding'
      preLoaderRoute: typeof SellOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/team': {
      id: '/sell/team'
      path: '/sell/team'
      fullPath: '/sell/team'
      preLoaderRoute: typeof SellTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/$slug': {
      id: '/seller/$slug'
      path: '/seller/$slug'
      fullPath: '/seller/$slug'
      preLoaderRoute: typeof SellerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  PoliciesRoute: PoliciesRoute,
  SearchRoute: SearchRoute,
  SigninRoute: SigninRoute,
  ApiHealthRoute: ApiHealthRoute,
  CategorySlugRoute: CategorySlugRoute,
  OrdersIdRoute: OrdersIdRoute,
  ProductIdRoute: ProductIdRoute,
  ReturnsNewRoute: ReturnsNewRoute,
  SellAddProductRoute: SellAddProductRoute,
  SellBulkStockRoute: SellBulkStockRoute,
  SellBulkUploadRoute: SellBulkUploadRoute,
  SellOnboardingRoute: SellOnboardingRoute,
  SellTeamRoute: SellTeamRoute,
  SellerSlugRoute: SellerSlugRoute,
  SellIndexRoute: SellIndexRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
